"""add_unique_constraint_to_user

Revision ID: 19e1a127a414
Revises: 46ec990736d2
Create Date: 2026-03-27 15:31:29.328456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e1a127a414'
down_revision: Union[str, Sequence[str], None] = '46ec990736d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_email_phone', 'users', ['email', 'phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_email_phone', 'users', type_='unique')
    # ### end Alembic commands ###
