"""Add last_message to groups

Revision ID: 2c4f6a7b9e2e
Revises: f5a92263eb44
Create Date: 2026-02-23 21:03:28.079915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4f6a7b9e2e'
down_revision: Union[str, Sequence[str], None] = 'f5a92263eb44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('groups', sa.Column('last_message', sa.String(length=255), nullable=True))
    op.add_column('groups', sa.Column('last_message_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'last_message_time')
    op.drop_column('groups', 'last_message')
    # ### end Alembic commands ###
