"""update groups table

Revision ID: 3f166f0a27fa
Revises: 2c4f6a7b9e2e
Create Date: 2026-03-07 11:41:05.983976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3f166f0a27fa'
down_revision: Union[str, Sequence[str], None] = '2c4f6a7b9e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('groups', 'last_message_time')
    op.drop_column('groups', 'last_message')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('last_message', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('groups', sa.Column('last_message_time', mysql.DATETIME(), nullable=True))
    op.drop_column('groups', 'created_at')
    # ### end Alembic commands ###
