"""Add explicit msg persist fields

Revision ID: 46ec990736d2
Revises: 2cba98e19f12
Create Date: 2026-03-24 21:04:13.766716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ec990736d2'
down_revision: Union[str, Sequence[str], None] = '2cba98e19f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_content', sa.String(length=255), nullable=True))
    op.add_column('messages', sa.Column('reply_to_sender', sa.String(length=255), nullable=True))
    op.drop_constraint(op.f('messages_ibfk_4'), 'messages', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('messages_ibfk_4'), 'messages', 'messages', ['reply_to_id'], ['id'])
    op.drop_column('messages', 'reply_to_sender')
    op.drop_column('messages', 'reply_to_content')
    # ### end Alembic commands ###
