"""update groups table added created_at

Revision ID: d4ef3d035b3a
Revises: f0fd3d2671f4
Create Date: 2026-03-07 11:55:10.766027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd4ef3d035b3a'
down_revision: Union[str, Sequence[str], None] = 'f0fd3d2671f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('groups', 'last_message')
    op.drop_column('groups', 'last_message_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('last_message_time', mysql.DATETIME(), nullable=False))
    op.add_column('groups', sa.Column('last_message', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('groups', 'created_at')
    # ### end Alembic commands ###
