"""remove_redundant_unique_from_email

Revision ID: eaaf9123261b
Revises: 19e1a127a414
Create Date: 2026-03-27 15:34:38.998806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaaf9123261b'
down_revision: Union[str, Sequence[str], None] = '19e1a127a414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('email'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
