"""update groups table

Revision ID: f0fd3d2671f4
Revises: 3f166f0a27fa
Create Date: 2026-03-07 11:53:12.998898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f0fd3d2671f4'
down_revision: Union[str, Sequence[str], None] = '3f166f0a27fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'last_message_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'last_message_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
